# https://travis-ci.com/tczorro/SpSaddle
language: python
python:
    - 2.7
    - 3.5

install:
    - pip install -r requirements.txt
    - python setup.py install

script:
    - nosetests -v saddle/test

notifications:
  email: false
