# https://travis-ci.com/tczorro/SpSaddle
language: python
python:
    - 3.6

install:
    - pip install -r requirements.txt
    - pip install pylint
    - python setup.py install

script:
    - nosetests -v saddle/test
    - pylint saddle --errors-only

notifications:
  email: false
